In [73]:
import numpy as np

import matplotlib.ticker as mtick
import wf_psf as wf
import matplotlib.pyplot as plt
import matplotlib as mpl

In [74]:
base_path = '/Users/ec270266/Documents/Phd/Euclid/dev/phase_retrieval/wf-psf/papers/phase_retrieval_2024/data/paper_output_v1/'
log_folder = 'log-files/'
metric_base_path = '/Users/ec270266/Documents/Phd/Euclid/dev/phase_retrieval/wf-psf/papers/phase_retrieval_2024/data/paper_output_v1/full_metrics/'

metrics_base_id_full = 'metrics-poly_wf_PR_NewPRoj_12_cycles_full_eval_v'
metrics_base_id_param = 'metrics-poly_wf_PR_NewPRoj_12_cycles_onlyparam_eval_v'
    

# WFE results

In [75]:
cycles = ['2', '5', '9', '12']
runs = ['0', '2', '3']

opd_results_full = np.zeros((len(cycles), len(runs)))
opd_results_param = np.zeros((len(cycles), len(runs)))

opd_std_full = np.zeros((len(cycles), len(runs)))
opd_std_param = np.zeros((len(cycles), len(runs)))

for cycle_idx, cycle_ in enumerate(cycles):
    for run_idx, run_ in enumerate(runs):
        loaded_metrics_full = np.load(
            metric_base_path + metrics_base_id_full + run_ + '_' + 'cycle' + cycle_ + '.npy',
            allow_pickle=True
        )[()]
        loaded_metrics_param = np.load(
            metric_base_path + metrics_base_id_param + run_ + '_' + 'cycle' + cycle_ + '.npy',
            allow_pickle=True
        )[()]
        opd_results_param[cycle_idx, run_idx] = loaded_metrics_param['test_metrics']['opd_metric']['rel_rmse_opd']
        opd_results_full[cycle_idx, run_idx] = loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_opd']
        opd_std_param[cycle_idx, run_idx] = loaded_metrics_param['test_metrics']['opd_metric']['rel_rmse_std_opd']
        opd_std_full[cycle_idx, run_idx] = loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_std_opd']


In [76]:
def argmedian(a, axis=0, keepdims=False):
    # Return the indices of the median values along an axis.
    a = np.asarray(a)
    idx = np.argsort(a, axis=axis)
    mid = a.shape[axis] // 2
    if a.shape[axis] % 2 == 0:
        mid -= 1
    arg_median = np.take(idx, mid, axis=axis)
    if keepdims:
        arr_median = np.zeros_like(a)
        for i in range(a.T.shape[axis]):
            arr_median[i, arg_median[i]] = 1
        return arr_median
    return arg_median

In [77]:
print("OPD resutls only param:")
print(opd_results_param)
print("Median:")
print(np.median(opd_results_param, axis=1))
print("Best:")
print(np.min(opd_results_param, axis=1))
print()
print("std:")
print(opd_std_param)

argmedian(opd_results_param, axis=1, keepdims=True)

OPD resutls only param:
[[67.33164197 66.33994271 62.97605811]
 [ 9.82910752 12.34539854  8.70627251]
 [ 3.66677781  4.86275721  3.35265379]
 [ 3.42809692  4.3501334   3.05819326]]
Median:
[66.33994271  9.82910752  3.66677781  3.42809692]
Best:
[62.97605811  8.70627251  3.35265379  3.05819326]

std:
[[ 7.2118728  15.23044698 22.50125013]
 [ 4.55504094  5.70405548  3.15639104]
 [ 0.96008725  1.29461812  1.12710553]
 [ 0.86154579  1.30232267  1.01330553]]


array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [78]:
print("OPD resutls full:")
print(opd_results_full)
print("Median:")
print(np.median(opd_results_full, axis=1))
print("Best:")
print(np.min(opd_results_full, axis=1))
print()
print("std:")
print(opd_std_full)

argmedian(opd_results_full, axis=1, keepdims=True)

OPD resutls full:
[[122.7231506  126.47104136 108.42153425]
 [ 12.68071959  17.68795772  12.28127203]
 [  6.57132129   7.36450991   6.31439143]
 [  6.44178406   7.02141704   6.11745393]]
Median:
[122.7231506   12.68071959   6.57132129   6.44178406]
Best:
[108.42153425  12.28127203   6.31439143   6.11745393]

std:
[[18.22513845 18.44711555 31.07157074]
 [ 3.51336306  6.29548105  3.18702624]
 [ 1.24047199  1.45951434  1.56404792]
 [ 1.19425176  1.41159877  1.48888293]]


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

# Pixel x3 results (SR)

In [79]:

pix_results_param = np.zeros((len(cycles), len(runs)))
pix_results_full = np.zeros((len(cycles), len(runs)))
pix_std_param = np.zeros((len(cycles), len(runs)))
pix_std_full = np.zeros((len(cycles), len(runs)))


for cycle_idx, cycle_ in enumerate(cycles):
    for run_idx, run_ in enumerate(runs):
        loaded_metrics_full = np.load(
            metric_base_path + metrics_base_id_full + run_ + '_' + 'cycle' + cycle_ + '.npy',
            allow_pickle=True
        )[()]
        loaded_metrics_param = np.load(
            metric_base_path + metrics_base_id_param + run_ + '_' + 'cycle' + cycle_ + '.npy',
            allow_pickle=True
        )[()]
        pix_results_param[cycle_idx, run_idx] = loaded_metrics_param['test_metrics']['shape_results_dict']['rel_pix_rmse']
        pix_results_full[cycle_idx, run_idx] = loaded_metrics_full['test_metrics']['shape_results_dict']['rel_pix_rmse']
        pix_std_param[cycle_idx, run_idx] = loaded_metrics_param['test_metrics']['shape_results_dict']['rel_pix_rmse_std']
        pix_std_full[cycle_idx, run_idx] = loaded_metrics_full['test_metrics']['shape_results_dict']['rel_pix_rmse_std']

In [80]:
print("SR pix results only param:")
print(pix_results_param)
print("Median:")
print(np.median(pix_results_param, axis=1))
print("Best:")
print(np.min(pix_results_param, axis=1))
print()
print("std:")
print(pix_std_param)

argmedian(pix_results_param, axis=1, keepdims=True)

SR pix results only param:
[[12.0516412  12.05294803  9.78810415]
 [ 1.4747316   1.84320044  1.35734798]
 [ 0.68598581  0.79791835  0.68585854]
 [ 0.66172881  0.68901442  0.66498909]]
Median:
[12.0516412   1.4747316   0.68598581  0.66498909]
Best:
[9.78810415 1.35734798 0.68585854 0.66172881]

std:
[[8.51369724 6.52998984 4.91315648]
 [1.28818005 1.36267971 1.04456432]
 [0.2950774  0.31115452 0.26136073]
 [0.23715945 0.24925892 0.21725297]]


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [81]:
print("SR pix results full:")
print(pix_results_full)
print("Median:")
print(np.median(pix_results_full, axis=1))
print("Best:")
print(np.min(pix_results_full, axis=1))
print()
print("std:")
print(pix_std_full)

argmedian(pix_results_full, axis=1, keepdims=True)

SR pix results full:
[[5.09619378 3.53415459 2.27102321]
 [0.77565992 0.82558552 0.78416811]
 [0.70818109 0.74203932 0.67036618]
 [0.69622207 0.69437446 0.69355424]]
Median:
[3.53415459 0.78416811 0.70818109 0.69437446]
Best:
[2.27102321 0.77565992 0.67036618 0.69355424]

std:
[[2.83070263 2.00920422 1.06086191]
 [0.25946023 0.22864847 0.2175417 ]
 [0.18264516 0.19248195 0.17169117]
 [0.19550552 0.19709759 0.19481297]]


array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

# Pixel x1 results (LR)

In [95]:
pix_x1_results_param = np.zeros((len(cycles), len(runs)))
pix_x1_results_full = np.zeros((len(cycles), len(runs)))
pix_x1_std_param = np.zeros((len(cycles), len(runs)))
pix_x1_std_full = np.zeros((len(cycles), len(runs)))


for cycle_idx, cycle_ in enumerate(cycles):
    for run_idx, run_ in enumerate(runs):
        loaded_metrics_full = np.load(
            metric_base_path + metrics_base_id_full + run_ + '_' + 'cycle' + cycle_ + '.npy',
            allow_pickle=True
        )[()]
        loaded_metrics_param = np.load(
            metric_base_path + metrics_base_id_param + run_ + '_' + 'cycle' + cycle_ + '.npy',
            allow_pickle=True
        )[()]
        pix_x1_results_param[cycle_idx, run_idx] = loaded_metrics_param['test_metrics']['poly_metric']['rel_rmse']
        pix_x1_results_full[cycle_idx, run_idx] = loaded_metrics_full['test_metrics']['poly_metric']['rel_rmse']
        pix_x1_std_param[cycle_idx, run_idx] = loaded_metrics_param['test_metrics']['poly_metric']['std_rel_rmse']
        pix_x1_std_full[cycle_idx, run_idx] = loaded_metrics_full['test_metrics']['poly_metric']['std_rel_rmse']

In [96]:
print("x1 pix results full:")
print(pix_x1_results_full)
print("Median:")
print(np.median(pix_x1_results_full, axis=1))
print("Best:")
print(np.min(pix_x1_results_full, axis=1))
print()
print("std:")
print(pix_x1_std_full)

argmedian(pix_x1_results_full, axis=1, keepdims=True)

x1 pix results full:
[[1.47681609 1.33681907 1.15864055]
 [0.38527198 0.38685954 0.35134812]
 [0.27108324 0.28829817 0.28204578]
 [0.26919808 0.28408723 0.27099182]]
Median:
[1.33681907 0.38527198 0.28204578 0.27099182]
Best:
[1.15864055 0.35134812 0.27108324 0.26919808]

std:
[[0.54551169 0.44446942 0.47090551]
 [0.15993295 0.1516394  0.14503395]
 [0.13553277 0.14033003 0.13304532]
 [0.13356414 0.1370353  0.13142248]]


array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [98]:
print("x1 pix results param:")
print(pix_x1_results_param)
print("Median:")
print(np.median(pix_x1_results_param, axis=1))
print("Best:")
print(np.min(pix_x1_results_param, axis=1))
print()
print("std:")
print(pix_x1_std_param)

argmedian(pix_x1_results_param, axis=1, keepdims=True)

x1 pix results param:
[[10.8906127  11.80408603  9.88136999]
 [ 1.63134825  1.5042258   1.22881126]
 [ 0.46603717  0.4652714   0.42771315]
 [ 0.3676022   0.38583796  0.35118346]]
Median:
[10.8906127  1.5042258  0.4652714  0.3676022]
Best:
[9.88136999 1.22881126 0.42771315 0.35118346]

std:
[[8.35475353 6.23966252 4.95878986]
 [1.29832784 1.20245504 1.09074855]
 [0.30338971 0.32105123 0.2509276 ]
 [0.20158691 0.22114535 0.17799426]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

# Original WaveDfiff resutls

In [82]:
metrics_base_path = '/Users/ec270266/Documents/Phd/Euclid/dev/phase_retrieval/wf-psf/papers/phase_retrieval_2024/data/paper_output_v1/metrics/'


In [83]:
loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_std_opd']

1.4888829305209932

In [84]:
final_full_opd = np.zeros((len(runs),))
final_full_opd_std = np.zeros((len(runs),))

original_opd = np.zeros((len(runs),))
original_opd_std = np.zeros((len(runs),))

no_reset_opd = np.zeros((len(runs),))
no_reset_opd_std = np.zeros((len(runs),))

for run_idx, run_ in enumerate(runs):
    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_NewPRoj_12_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    final_full_opd[run_idx] = loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_opd']
    final_full_opd_std[run_idx] = loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_std_opd']

    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_benchmark_2_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    original_opd[run_idx] = loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_opd']
    original_opd_std[run_idx] = loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_std_opd']

    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_no_reset_12_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    no_reset_opd[run_idx] = loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_opd']
    no_reset_opd_std[run_idx] = loaded_metrics_full['test_metrics']['opd_metric']['rel_rmse_std_opd']

In [85]:
print(np.around(final_full_opd, decimals=2), "+/-", np.around(final_full_opd_std, decimals=2))
print(np.around(original_opd, decimals=2), "+/-", np.around(original_opd_std, decimals=2))
# print(np.around(no_reset_opd, decimals=2), "+/-", np.around(no_reset_opd_std, decimals=2))

[6.44 7.02 6.12] +/- [1.19 1.41 1.49]
[29.14 79.7  25.11] +/- [11.91 15.16  7.55]


In [86]:
final_full_pix = np.zeros((len(runs),))
final_full_pix_std = np.zeros((len(runs),))

original_pix = np.zeros((len(runs),))
original_pix_std = np.zeros((len(runs),))

no_reset_pix = np.zeros((len(runs),))
no_reset_pix_std = np.zeros((len(runs),))

for run_idx, run_ in enumerate(runs):
    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_NewPRoj_12_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    final_full_pix[run_idx] = loaded_metrics_full['test_metrics']['poly_metric']['rel_rmse']
    final_full_pix_std[run_idx] = loaded_metrics_full['test_metrics']['poly_metric']['std_rel_rmse']

    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_benchmark_2_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    original_pix[run_idx] = loaded_metrics_full['test_metrics']['poly_metric']['rel_rmse']
    original_pix_std[run_idx] = loaded_metrics_full['test_metrics']['poly_metric']['std_rel_rmse']

    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_no_reset_12_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    no_reset_pix[run_idx] = loaded_metrics_full['test_metrics']['poly_metric']['rel_rmse']
    no_reset_pix_std[run_idx] = loaded_metrics_full['test_metrics']['poly_metric']['std_rel_rmse']

In [87]:
print(np.around(final_full_pix, decimals=2), "+/-", np.around(final_full_pix_std, decimals=2))
print(np.around(original_pix, decimals=2), "+/-", np.around(original_pix_std, decimals=2))
# print(np.around(no_reset_pix, decimals=2), "+/-", np.around(no_reset_pix_std, decimals=2))

[0.27 0.28 0.27] +/- [0.13 0.14 0.13]
[0.42 0.54 0.39] +/- [0.18 0.19 0.18]


In [88]:
final_full_pix_SR = np.zeros((len(runs),))
final_full_pix_SR_std = np.zeros((len(runs),))

original_pix_SR = np.zeros((len(runs),))
original_pix_SR_std = np.zeros((len(runs),))

no_reset_pix_SR = np.zeros((len(runs),))
no_reset_pix_SR_std = np.zeros((len(runs),))

for run_idx, run_ in enumerate(runs):
    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_NewPRoj_12_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    final_full_pix_SR[run_idx] = loaded_metrics_full['test_metrics']['shape_results_dict']['rel_pix_rmse']
    final_full_pix_SR_std[run_idx] = loaded_metrics_full['test_metrics']['shape_results_dict']['rel_pix_rmse_std']

    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_benchmark_2_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    original_pix_SR[run_idx] = loaded_metrics_full['test_metrics']['shape_results_dict']['rel_pix_rmse']
    original_pix_SR_std[run_idx] = loaded_metrics_full['test_metrics']['shape_results_dict']['rel_pix_rmse_std']

    loaded_metrics_full = np.load(
            metrics_base_path + 'metrics-poly_wf_PR_no_reset_12_cycles_v' + run_ + '.npy',
            allow_pickle=True
        )[()]
    no_reset_pix_SR[run_idx] = loaded_metrics_full['test_metrics']['shape_results_dict']['rel_pix_rmse']
    no_reset_pix_SR_std[run_idx] = loaded_metrics_full['test_metrics']['shape_results_dict']['rel_pix_rmse_std']

In [89]:
print(np.around(final_full_pix_SR, decimals=2), "+/-", np.around(final_full_pix_SR_std, decimals=2))
print(np.around(original_pix_SR, decimals=2), "+/-", np.around(original_pix_SR_std, decimals=2))
# print(np.around(no_reset_pix_SR, decimals=2), "+/-", np.around(no_reset_pix_SR_std, decimals=2))

[0.7  0.69 0.69] +/- [0.2  0.2  0.19]
[0.89 1.09 0.84] +/- [0.25 0.21 0.23]
